// UI
#define UI_FONT_COLOR Color(0, 0, 0)
#define UI_FONT_PATH "C:/Windows/Fonts/segoeui.ttf"
#define UI_FONT_SIZE 24
#define UI_FONT_SMALL_SIZE 16
#define UI_BACKGROUND_COLOR Color(255, 255, 255)
#define UI_TEXT_SPACING 10
#define UI_PLAYER_CUSTOMIZATION_WIDTH 400
#define UI_PLAYER_CUSTOMIZATION_HEIGHT 200
#define UI_PLAYER_CUSTOMIZATION_MODIFY_VALUE 4

// Game
#define GAME_UPDATE_INTERVAL 10
#define GAME_TITLE "All them Pixels!"
#define GAME_FADE_TIME 2000 // Milliseconds

// Player
#define PLAYER_SIZE 20
#define PLAYER_AIM_BOX_SIZE 4
#define PLAYER_COLOR Color(0, 0, 0)

// Joytstick
#define GAMEPAD_A 0
#define GAMEPAD_B 1
#define GAMEPAD_X 2
#define GAMEPAD_y 3
#define GAMEPAD_LB 4
#define GAMEPAD_RB 5
#define GAMEPAD_BACK 6
#define GAMEPAD_START 7
#define GAMEPAD_JOYSTICK_LEFT 8
#define GAMEPAD_JOYSTICK_RIGHT 9

// World
#define WORLD_LAYERS 2
#define WORLD_VIEW_WIDTH 1440
#define WORLD_VIEW_HEIGHT 900
#define WORLD_TERRITORY_RADIUS 2048
#define WORLD_TERRITORY_SPACING 0

// Territory
#define TERRITORY_CELL_SIZE 50.0f
#define TERRITORY_TILE_SIZE 10
#define TERRITORY_ENEMY_AURA_SIZE 5 // Layers.
#define TERRITORY_ENEMY_AURA_COLOR Color(0, 0, 0);
#define TERRITORY_PROBE_COUNT 16
#define TERRITORY_FLOOR_TILES_GRAYNESS 30
#define TERRITORY_BORDER_TILES_REDNESS 40
#define TERRITORY_SAFE_TILES_GREENESS 40

// Skill related constants.
#define SKILL_CHANGE_COOLDOWN 200
#define SKILL_MODIFY_COOLDOWN 20
#define	PLAYER_BASE_HP 10000
#define PLAYER_BASE_SPEED 1
#define PLAYER_BASE_WEAPON_COOLDOWN 100
#define PLAYER_BASE_WEAPON_DAMAGE 1000
#define PLAYER_BASE_WEAPON_PIERCING 10
#define PLAYER_BASE_WEAPON_SPEED 5
#define PLAYER_BASE_WEAPON_SPREAD 1
#define PLAYER_BASE_WEAPON_TTL 55