// UI
#define UI_FONT_COLOR Color(0, 0, 0)
#define UI_FONT_PATH "C:/Windows/Fonts/segoeui.ttf"
#define UI_FONT_SIZE 24
#define UI_FONT_SMALL_SIZE 16
#define UI_BACKGROUND_COLOR Color(255, 255, 255)
#define UI_TEXT_SPACING 10

//World
#define WORLD_LAYERS 2

// Territory
#define TERRITORY_CELL_SIZE 50.0f
#define TERRITORY_TILE_SIZE 10

// Skill related constants.
#define SKILL_CHANGE_COOLDOWN 200
#define SKILL_MODIFY_COOLDOWN 20
#define	PLAYER_BASE_HP 10000
#define PLAYER_BASE_SPEED 1
#define PLAYER_BASE_WEAPON_COOLDOWN 100
#define PLAYER_BASE_WEAPON_DAMAGE 1000
#define PLAYER_BASE_WEAPON_PIERCING 10
#define PLAYER_BASE_WEAPON_SPEED 5
#define PLAYER_BASE_WEAPON_SPREAD 1
#define PLAYER_BASE_WEAPON_TTL 55